Реализовано задание Fighters
1mumble1/travelline_practice pull request #7
Opened 2024-04-11 14:26 UTC by 1mumble1

2024-04-21 16:23 UTC, VladTL commented
Когда заканчиваешь выбор бойца, не хватает сообщения вроде: "Боец такой-то с такими-то характеристиками был успешно добавлен"

2024-04-21 16:42 UTC, VladTL requested changes

2024-04-21 16:42 UTC, VladDotMe commented on Fighters/Fighters/GameMaster.cs
> +                if (commandInput == null || (commandInput != AddFighter && commandInput != Play))
лучше писать is null вместо == null и is not null вместо != null

2024-04-21 16:42 UTC, VladDotMe commented on Fighters/Fighters/GameMaster.cs
> +        private List<IFighter> fighters = new List<IFighter>();
private readonly List<IFighter> _fighters = [];
можно так

От самого важного к наименее важному:
1. Название приватных полей класса именуем с _
2. Поле можно сделать readonly
3. Можно использовать = []; вместо написания полной конструкции new List<IFighter>()...

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/GameMaster.cs
> +    public class GameMaster
Помнишь про принцип единственной ответственности? У тебя класс GameMaster сейчас делает две вещи:
1. Создает бойцов (по сути подготавливает игру)
2. Непосредственно проводит битву

Правильнее будет метод подготовки битвы вынести в отдельный класс.

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/GameMaster.cs
> +            fighters.Sort(delegate(IFighter first, IFighter second)
Лучше использовать OrderBy из LINQ
1. Намного более популярный, если честно впервые вижу чтобы использовали Sort
2. Легче читаемый
3. Более быстрый и стабильный https://stackoverflow.com/questions/1832684/c-sharp-sort-and-orderby-comparison

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/Models/Armors/Breastplate.cs
> +﻿using System;
Лишние usings во всех моделях

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/GameMaster.cs
> +            throw new UnreachableException();
Зачем? Можешь безопасно убрать, компилятор умный, он итак понимает, что до сюда код никогда не дойдет)

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/FightersCreator.cs
> +            while (name == null)
string? name;
            while ((name = Console.ReadLine()) is null)
            {
                Console.WriteLine("Невалидное имя для бойца, попробуйте еще раз");
            }
            
            А можно так)

2024-04-21 16:42 UTC, VladTL commented on Fighters/Fighters/GameMaster.cs
> +                    while (opponentNumber == i)
Честно? Выглядит как костыль :)

Можно создать список с допустимыми индексами (все живые файтеры кроме текущего) и выбрать оттуда один индекс кого будем атаковать.

2024-04-30 20:50 UTC, 1mumble1 commented
1. Добавлен вывод сообщения для юзера после создания бойца
2. Исправлено ==null на is null
3. Исправлено наименование приватных полей, список readonly, исправлена конструкция на = []
4. Вынесен класс CommsndHandler из класса GameMaster
5. Исправлена сортировка списка с помощью OrderByDescending
6. Убраны лишние using'и
7. Убрана лишний выброс исключения
8. Улучшен ввод имени бойца
9. Исправлен подбор противника с помощью массива индексов живых бойцов, кроме текущего

2024-05-01 14:06 UTC, VladTL commented on Fighters/Fighters/Program.cs
> +}
лишняя }, и в целом программа не компилируется, в других файлах тоже есть ошибки, проверь все.

2024-05-01 14:07 UTC, VladTL requested changes
Программа не компилируется, проверь все

2024-05-12 16:57 UTC, VladTL approved these changes

2024-05-12 16:57 UTC, VladTL commented on Fighters/Fighters/Utils/CommandHandler.cs
> +            if (commandInput == Play)
Впринципе мелочь, но мне кажется, что здесь лучше поменять местами блоки Play и AddFighter, т.к. логически вначале идет вызов AddPlayer а потом Play. Когда делаешь ревью кода, немного цепляет глаз то, что мы уже проверяем количество файтеров хотя еще не вызывали код по их добавлению.

2024-05-12 16:57 UTC, VladTL commented on Fighters/Fighters/Models/Fighters/Fighter.cs
> +    public IWeapon Weapon { get; set; }
Тут тоже сеттеры лишние убрать. Возьми за правило, что когда пишешь код, нужно делать его по максимуму защищенным: т.е. не пишем сеттеры если нет в них необходимости, не делаем методы публичными если не используются из вне и т.д. 

Ты можешь либо сразу прикинуть будет ли использоваться сеттер и в зависимости от этого писать его или не писать, либо по умолчанию не писать и писать уже по-мере необходимости. 
А еще Rider и Resharper подсвечивают когда что-то не используется, очень удобно.

2024-05-12 16:57 UTC, VladTL commented on Fighters/Fighters/Utils/GameMaster.cs
> +                for (int j = 0; j < sortedFighters.Count; j++)
Сгруппировать бы получение индекса с генерацией свободных индексов, т.е. будет:
```             
List<int> indexesOfAliveFighters = [];
for (int j = 0; j < sortedFighters.Count; j++)
{
    if (j == i)
    {
       continue;
    }
    indexesOfAliveFighters.Add(j);
}
int defenderIndex = indexesOfAliveFighters[Random.Shared.Next(0, indexesOfAliveFighters.Count)];
```

2024-05-12 16:57 UTC, VladTL commented
В целом неплохо, поправь то что написал и можешь сливать.

2024-05-16 19:50 UTC, merged